# fly.toml file generated for techswipe-backend on 2023-03-13T11:48:11+05:30

app = "techswipe-backend"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"
processes = []

[env]
  PORT = "8080"
  MONGODB_URL = "mongodb+srv://techswipe:TechSwipe%40Pesto@cluster0.cclzckx.mongodb.net/techswipe"
  GITHUB_CLIENT_ID = "48feeaa7d2b0659ee9ba"
  GITHUB_CLIENT_SECRET = "95401311e48eea08a535035aaa49be07b8bfb2e8"
  LINKEDIN_CLIENT_ID = "86k9sqgwwmgzxb"
  LINKEDIN_CLIENT_SECRET = "IRVncQumyAIzPiU9" 
  JWT_KEY = "t3chswip3@p3sto"
  BASE_URL_FRONTEND="https://techswipe.vercel.app/"
  BASE_URL=""
  GEOAPIFY_API_KEY="112eddcf23924c998ccb79ed3f2c3b6c"
  
[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
